# Generated by Django 3.2.2 on 2021-05-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(error_messages={'blank': 'Title cannot be empty'}, max_length=200)),
                ('complete', models.BooleanField(default=False)),
                ('detail', models.TextField(blank=True, max_length=500)),
                ('priority', models.IntegerField(choices=[(0, 'Low Priority'), (1, 'Medium Priority'), (2, 'High Priority')], default=1)),
            ],
        ),
    ]
