# Generated by Django 3.2.2 on 2021-05-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='priority',
            field=models.IntegerField(choices=[(2, 'High Priority'), (1, 'Medium Priority'), (0, 'Low Priority')], default=1),
        ),
    ]
